# 基础镜像
FROM redis
# author
MAINTAINER ddogring

# 挂载目录
VOLUME /home/ddogring/redis
# 创建目录
RUN mkdir -p /home/ddogring/redis
# 指定路径
WORKDIR /home/ddogring/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/ddogring/redis/redis.conf
