# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ddogring

# 挂载目录
VOLUME /home/ddogring
# 创建目录
RUN mkdir -p /home/ddogring
# 指定路径
WORKDIR /home/ddogring
# 复制jar文件到路径
COPY ./jar/ddogring-modules-job.jar /home/ddogring/ddogring-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","ddogring-modules-job.jar"]