# 基础镜像
FROM nginx
# author
MAINTAINER ddogring

# 挂载目录
VOLUME /home/ddogring/projects/ddogring-ui
# 创建目录
RUN mkdir -p /home/ddogring/projects/ddogring-ui
# 指定路径
WORKDIR /home/ddogring/projects/ddogring-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/ddogring/projects/ddogring-ui
