# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ddogring

# 挂载目录
VOLUME /home/ddogring
# 创建目录
RUN mkdir -p /home/ddogring
# 指定路径
WORKDIR /home/ddogring
# 复制jar文件到路径
COPY ./jar/ddogring-visual-monitor.jar /home/ddogring/ddogring-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","ddogring-visual-monitor.jar"]